app_name: tonic
env: development

sentry:
  enabled: False

kafka:
  enabled: False

statsd:
  enabled: False

logging:
  formatters:
    - name: pretty
      format: text
      color: true
  handlers:
    - name: console
      formatter: pretty
  loggers:
    - name: default
      handlers: [console]
      level: DEBUG
    - name: topic
      handlers: [console]
      level: DEBUG
